### ISSUE TITLE
Possibly any relation to the Dell WD19S?

### ISSUE THREAD

**Issue by parkerlreed** [edrose/dell-dock-audio-fix#3]
I have the WD19S with three monitors attached

The lsusb relating to Realtek is

```
Bus 005 Device 002: ID 0bda:5487 Realtek Semiconductor Corp. Dell dock
Bus 005 Device 004: ID 0bda:5413 Realtek Semiconductor Corp. Dell dock
Bus 006 Device 002: ID 0bda:0487 Realtek Semiconductor Corp. Dell dock
Bus 006 Device 004: ID 0bda:0413 Realtek Semiconductor Corp. Dell dock
Bus 006 Device 007: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
```

For some reason even on the ALSA layer, I only have access to one of the DP outputs for audio (Note the Device 3 next to HDMI)

```
parker@fedora:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Generic [HD-Audio Generic], device 3: HDMI 0 [Q27q-10]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Generic_1 [HD-Audio Generic], device 0: ALC294 Analog [ALC294 Analog]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: Au [ThinkPad USB-C Dock Gen2 USB Au], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 3: Receiver [Zone 900 Receiver], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Using Pipewire, I have no access to the other two DisplayPort outputs for audio. 

Unsure if this repo has any affect for this since it's a different dock (And I'm using Pipewire instead of Pulseaudio)

**Comment by parkerlreed** [comment]
As far as Pipewire is concerned I only have that one "HDMI" output (It's actually one of the DisplayPort)

![image](https://github.com/edrose/dell-dock-audio-fix/assets/841440/940a0083-077d-4507-b544-62bd90f5616b)

**Comment by edrose** [comment]
This repo was just a minor configuration change to PulseAudio which has since been fixed upstream. As you're not using pulse audio, this repo is likely completely unrelated to your issue.

I don't use Dell docks or Arch Linux anymore, and I don't have any experience with pipewire. Sorry, I can't be much help.

**Comment by parkerlreed** [comment]
Thanks!
